apiVersion: v1
kind: List
items:

- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: agent-sa

- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: agent-role
  rules:
    - apiGroups: ["coordination.k8s.io"]
      resources: ["leases"]
      verbs: ["get", "watch", "list", "create", "update", "delete", "patch"]
    - apiGroups: [""]
      resources: ["pods"]
      verbs: ["get", "watch", "list", "patch"]

- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: agent-role-binding
  subjects:
    - kind: ServiceAccount
      name: agent-sa
  roleRef:
    kind: Role
    name: agent-role
    apiGroup: rbac.authorization.k8s.io

- apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    name: leader-elector
    labels:
      app: elector
  spec:
    selector:
      matchLabels:
        app: elector
    template:
      metadata:
        labels:
          app: elector
      spec:
        restartPolicy: Always
        serviceAccountName: agent-sa
        containers:
          - name: elector
            image: steveww/leader-elector
            args: ["-election=foo", "-http=0.0.0.0:5002"]
            ports:
              - name: http
                containerPort: 5002
